name: flutter_master_chat_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  firebase_core: ^2.0.0  # Downgraded to ensure compatibility
  firebase_auth: ^4.0.0    # Downgraded to match firebase_core
  cloud_firestore: ^4.0.0 # Adjusted for better compatibility with firebase_core
  flutter_progress_hud: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - images/
